global:
  scrape_interval: 5s

scrape_configs:
  - job_name: order
    static_configs:
      - targets: ["order:8080"]

  - job_name: inventory
    static_configs:
      - targets: ["inventory:8080"]
